default:
  result_name: 'who_owns_mass'
  state: "MA"
  muni_ids: [274, 35]
  most_recent: FALSE
  company_count: 50000
  cosine_thresh: 0.85
  inds_thresh: 0.95
  zip_int_thresh: 1
  crs: 2249
  data_dir: 'data'
  companies_path: !expr file.path(data_dir, 'companies.csv')
  officers_path: !expr file.path(data_dir, 'officers.csv')
  alt_names_path: !expr file.path(data_dir, 'alternative_names.csv')
  parcels_remote: "https://s3.us-east-1.amazonaws.com/download.massgis.digital.mass.gov/gdbs/l3parcels/MassGIS_L3_Parcels_gdb.zip"
  assess_layer: 'L3_ASSESS'
  parcels_layer: 'L3_TAXPAR_POLY'
complete:
  inherits: default
  company_count: NULL
  muni_ids: NULL
